### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Freudy007** [geiszla/iOSLib#1]
Hello
in first : I like your IOSLib.

I'm french developer, and I try to acces to app data file system (/private/var/mobile/Containers/Data/Application/....). I can with c#, Jailbreak and SSH (USB & WIFI).
But I search a solution with c# and without jailbreak.
With your project and LibIMobileDevice I can acces to media path file system, but I can't acces to app data file system.

1 - Do you know if it is possible ?
2 - Do you have a method for listing Idevice directory ?

**Comment by ghost** [comment]
Hello,
This project is not in active development, but my library, inspired by this great one, provides much of the same functionality and is available at 
https://github.com/exaphaser/MK.MobileDevice.

In addition to everything provided by iOSLib functionality, my library also supports everything iTunes supports, including screenshots, icon management, app management, file browsing, and even WiFi syncing.
I also have backup and restore working, and I have reliable functions to enter/exit recovery. I spent over two months wiring the original code base, and it supports almost everything that iTunes supports. I built this library because I had a similar need for a library to do such things.

As for your specific questions, yes it is possible; this library is pure c# with a c++ native backend (you don't need to worry about this it is wrapped by c#, and does not need jailbreak. 

App data is accessed through the house arrest interface. My library has this partially implemented, and will be finished soon.

I am happy to provide support; my library is in active development.
Contact 
exaphaser@gmail.com
Or open an issue on my repository 
https://github.com/exaphaser/MK.MobileDevice

**Comment by Freudy007** [comment]
Thank you for your complete response.
I go to look and try this library

**Comment by ghost** [comment]
Good luck
